services:
  app:
    image: ghcr.io/nenecchuu/luminakra-sample-app:latest
    container_name: luminakra-app-prod
    restart: unless-stopped
    ports:
      - "8080:80"  # Expose on port 8080
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env.production
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - luminakra-codeinfra_proxy-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  storage_data:
    driver: local

networks:
  luminakra-codeinfra_proxy-network:
    external: true
