import defaultTheme from "tailwindcss/defaultTheme";
import type { Config } from "tailwindcss/types/config";

const spacing = {
  0: "0px",
  px: "1px",
  0.5: "2px",
  1: "4px",
  1.25: "5px",
  1.5: "6px",
  2: "8px",
  2.5: "10px",
  3: "12px",
  3.5: "14px",
  4: "16px",
  4.5: "18px",
  5: "20px",
  5.5: "22px",
  6: "24px",
  6.5: "26px",
  7: "28px",
  7.5: "30px",
  8: "32px",
  8.5: "34px",
  9: "36px",
  9.5: "38px",
  10: "40px",
  10.5: "42px",
  11: "44px",
  12: "48px",
  13: "52px",
  14: "56px",
  15: "60px",
  16: "64px",
  17: "68px",
  18: "72px",
  19: "76px",
  20: "80px",
  21: "84px",
  23: "92px",
  24: "96px",
  25: "100px",
  27: "108px",
  28: "112px",
  30: "120px",
  32: "128px",
  36: "144px",
  40: "160px",
  44: "176px",
  48: "192px",
  49: "196px",
  52: "208px",
  56: "224px",
  60: "240px",
  61: "244px",
  64: "256px",
  72: "288px",
  80: "320px",
  96: "324px",
  100: "400px",
  125: "500px",
  128: "512px",
  170: "680px",
};

export default {
  content: ["./resources/**/*.blade.php", "./resources/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",

      neutral: {
        0: "hsl(var(--color-neutral-0) / <alpha-value>)",
        1000: "hsl(var(--color-neutral-1000) / <alpha-value>)",
      },
      gray: {
        50: "hsl(var(--color-gray-50) / <alpha-value>)",
        100: "hsl(var(--color-gray-100) / <alpha-value>)",
        200: "hsl(var(--color-gray-200) / <alpha-value>)",
        300: "hsl(var(--color-gray-300) / <alpha-value>)",
        400: "hsl(var(--color-gray-400) / <alpha-value>)",
        500: "hsl(var(--color-gray-500) / <alpha-value>)",
        600: "hsl(var(--color-gray-600) / <alpha-value>)",
        700: "hsl(var(--color-gray-700) / <alpha-value>)",
        800: "hsl(var(--color-gray-800) / <alpha-value>)",
        900: "hsl(var(--color-gray-900) / <alpha-value>)",
      },
      red: {
        50: "hsl(var(--color-red-50) / <alpha-value>)",
        100: "hsl(var(--color-red-100) / <alpha-value>)",
        200: "hsl(var(--color-red-200) / <alpha-value>)",
        300: "hsl(var(--color-red-300) / <alpha-value>)",
        400: "hsl(var(--color-red-400) / <alpha-value>)",
        500: "hsl(var(--color-red-500) / <alpha-value>)",
        600: "hsl(var(--color-red-600) / <alpha-value>)",
        700: "hsl(var(--color-red-700) / <alpha-value>)",
        800: "hsl(var(--color-red-800) / <alpha-value>)",
        900: "hsl(var(--color-red-900) / <alpha-value>)",
      },
      orange: {
        50: "hsl(var(--color-orange-50) / <alpha-value>)",
        100: "hsl(var(--color-orange-100) / <alpha-value>)",
        200: "hsl(var(--color-orange-200) / <alpha-value>)",
        300: "hsl(var(--color-orange-300) / <alpha-value>)",
        400: "hsl(var(--color-orange-400) / <alpha-value>)",
        500: "hsl(var(--color-orange-500) / <alpha-value>)",
        600: "hsl(var(--color-orange-600) / <alpha-value>)",
        700: "hsl(var(--color-orange-700) / <alpha-value>)",
        800: "hsl(var(--color-orange-800) / <alpha-value>)",
        900: "hsl(var(--color-orange-900) / <alpha-value>)",
      },
      yellow: {
        50: "hsl(var(--color-yellow-50) / <alpha-value>)",
        100: "hsl(var(--color-yellow-100) / <alpha-value>)",
        200: "hsl(var(--color-yellow-200) / <alpha-value>)",
        300: "hsl(var(--color-yellow-300) / <alpha-value>)",
        400: "hsl(var(--color-yellow-400) / <alpha-value>)",
        500: "hsl(var(--color-yellow-500) / <alpha-value>)",
        600: "hsl(var(--color-yellow-600) / <alpha-value>)",
        700: "hsl(var(--color-yellow-700) / <alpha-value>)",
        800: "hsl(var(--color-yellow-800) / <alpha-value>)",
        900: "hsl(var(--color-yellow-900) / <alpha-value>)",
      },
      lime: {
        50: "hsl(var(--color-lime-50) / <alpha-value>)",
        100: "hsl(var(--color-lime-100) / <alpha-value>)",
        200: "hsl(var(--color-lime-200) / <alpha-value>)",
        300: "hsl(var(--color-lime-300) / <alpha-value>)",
        400: "hsl(var(--color-lime-400) / <alpha-value>)",
        500: "hsl(var(--color-lime-500) / <alpha-value>)",
        600: "hsl(var(--color-lime-600) / <alpha-value>)",
        700: "hsl(var(--color-lime-700) / <alpha-value>)",
        800: "hsl(var(--color-lime-800) / <alpha-value>)",
        900: "hsl(var(--color-lime-900) / <alpha-value>)",
      },
      green: {
        50: "hsl(var(--color-green-50) / <alpha-value>)",
        100: "hsl(var(--color-green-100) / <alpha-value>)",
        200: "hsl(var(--color-green-200) / <alpha-value>)",
        300: "hsl(var(--color-green-300) / <alpha-value>)",
        400: "hsl(var(--color-green-400) / <alpha-value>)",
        500: "hsl(var(--color-green-500) / <alpha-value>)",
        600: "hsl(var(--color-green-600) / <alpha-value>)",
        700: "hsl(var(--color-green-700) / <alpha-value>)",
        800: "hsl(var(--color-green-800) / <alpha-value>)",
        900: "hsl(var(--color-green-900) / <alpha-value>)",
      },
      cyan: {
        50: "hsl(var(--color-cyan-50) / <alpha-value>)",
        100: "hsl(var(--color-cyan-100) / <alpha-value>)",
        200: "hsl(var(--color-cyan-200) / <alpha-value>)",
        300: "hsl(var(--color-cyan-300) / <alpha-value>)",
        400: "hsl(var(--color-cyan-400) / <alpha-value>)",
        500: "hsl(var(--color-cyan-500) / <alpha-value>)",
        600: "hsl(var(--color-cyan-600) / <alpha-value>)",
        700: "hsl(var(--color-cyan-700) / <alpha-value>)",
        800: "hsl(var(--color-cyan-800) / <alpha-value>)",
        900: "hsl(var(--color-cyan-900) / <alpha-value>)",
      },
      teal: {
        50: "hsl(var(--color-teal-50) / <alpha-value>)",
        100: "hsl(var(--color-teal-100) / <alpha-value>)",
        200: "hsl(var(--color-teal-200) / <alpha-value>)",
        300: "hsl(var(--color-teal-300) / <alpha-value>)",
        400: "hsl(var(--color-teal-400) / <alpha-value>)",
        500: "hsl(var(--color-teal-500) / <alpha-value>)",
        600: "hsl(var(--color-teal-600) / <alpha-value>)",
        700: "hsl(var(--color-teal-700) / <alpha-value>)",
        800: "hsl(var(--color-teal-800) / <alpha-value>)",
        900: "hsl(var(--color-teal-900) / <alpha-value>)",
      },
      blue: {
        50: "hsl(var(--color-blue-50) / <alpha-value>)",
        100: "hsl(var(--color-blue-100) / <alpha-value>)",
        200: "hsl(var(--color-blue-200) / <alpha-value>)",
        300: "hsl(var(--color-blue-300) / <alpha-value>)",
        400: "hsl(var(--color-blue-400) / <alpha-value>)",
        500: "hsl(var(--color-blue-500) / <alpha-value>)",
        600: "hsl(var(--color-blue-600) / <alpha-value>)",
        700: "hsl(var(--color-blue-700) / <alpha-value>)",
        800: "hsl(var(--color-blue-800) / <alpha-value>)",
        900: "hsl(var(--color-blue-900) / <alpha-value>)",
      },
      indigo: {
        50: "hsl(var(--color-indigo-50) / <alpha-value>)",
        100: "hsl(var(--color-indigo-100) / <alpha-value>)",
        200: "hsl(var(--color-indigo-200) / <alpha-value>)",
        300: "hsl(var(--color-indigo-300) / <alpha-value>)",
        400: "hsl(var(--color-indigo-400) / <alpha-value>)",
        500: "hsl(var(--color-indigo-500) / <alpha-value>)",
        600: "hsl(var(--color-indigo-600) / <alpha-value>)",
        700: "hsl(var(--color-indigo-700) / <alpha-value>)",
        800: "hsl(var(--color-indigo-800) / <alpha-value>)",
        900: "hsl(var(--color-indigo-900) / <alpha-value>)",
      },
      purple: {
        50: "hsl(var(--color-purple-50) / <alpha-value>)",
        100: "hsl(var(--color-purple-100) / <alpha-value>)",
        200: "hsl(var(--color-purple-200) / <alpha-value>)",
        300: "hsl(var(--color-purple-300) / <alpha-value>)",
        400: "hsl(var(--color-purple-400) / <alpha-value>)",
        500: "hsl(var(--color-purple-500) / <alpha-value>)",
        600: "hsl(var(--color-purple-600) / <alpha-value>)",
        700: "hsl(var(--color-purple-700) / <alpha-value>)",
        800: "hsl(var(--color-purple-800) / <alpha-value>)",
        900: "hsl(var(--color-purple-900) / <alpha-value>)",
      },
      pink: {
        50: "hsl(var(--color-pink-50) / <alpha-value>)",
        100: "hsl(var(--color-pink-100) / <alpha-value>)",
        200: "hsl(var(--color-pink-200) / <alpha-value>)",
        300: "hsl(var(--color-pink-300) / <alpha-value>)",
        400: "hsl(var(--color-pink-400) / <alpha-value>)",
        500: "hsl(var(--color-pink-500) / <alpha-value>)",
        600: "hsl(var(--color-pink-600) / <alpha-value>)",
        700: "hsl(var(--color-pink-700) / <alpha-value>)",
        800: "hsl(var(--color-pink-800) / <alpha-value>)",
        900: "hsl(var(--color-pink-900) / <alpha-value>)",
      },
      base: {
        primary: "hsl(var(--color-base-primary) / <alpha-value>)",
        "light-primary": "hsl(var(--color-base-light-primary) / <alpha-value>)",
        "darker-primary":
          "hsl(var(--color-base-darker-primary) / <alpha-value>)",
        info: "hsl(var(--color-base-info) / <alpha-value>)",
        success: "hsl(var(--color-base-success) / <alpha-value>)",
        warning: "hsl(var(--color-base-warning) / <alpha-value>)",
        error: "hsl(var(--color-base-error) / <alpha-value>)",
      },
      outline: {
        primary: "hsl(var(--color-outline-primary) / <alpha-value>)",
        subtle: "hsl(var(--color-outline-subtle) / <alpha-value>)",
        darker: "hsl(var(--color-outline-darker) / <alpha-value>)",
        lighter: "hsl(var(--color-outline-lighter) / <alpha-value>)",
        default: "hsl(var(--color-outline-default) / <alpha-value>)",
        info: "hsl(var(--color-outline-info) / <alpha-value>)",
        success: "hsl(var(--color-outline-success) / <alpha-value>)",
        warning: "hsl(var(--color-outline-warning) / <alpha-value>)",
        error: "hsl(var(--color-outline-error) / <alpha-value>)",
      },
      background: {
        subtle: "hsl(var(--color-background-subtle) / <alpha-value>)",
        default: "hsl(var(--color-background-default) / <alpha-value>)",
        disabled: "hsl(var(--color-background-disabled) / <alpha-value>)",
        darker: "hsl(var(--color-background-darker) / <alpha-value>)",
        primary: "hsl(var(--color-background-primary) / <alpha-value>)",
        "light-primary":
          "hsl(var(--color-background-light-primary) / <alpha-value>)",
        "darker-primary":
          "hsl(var(--color-background-darker-primary) / <alpha-value>)",
        info: "hsl(var(--color-background-info) / <alpha-value>)",
        "light-info": "hsl(var(--color-background-light-info) / <alpha-value>)",
        "darker-info":
          "hsl(var(--color-background-darker-info) / <alpha-value>)",
        success: "hsl(var(--color-background-success) / <alpha-value>)",
        "light-success":
          "hsl(var(--color-background-light-success) / <alpha-value>)",
        "darker-success":
          "hsl(var(--color-background-darker-success) / <alpha-value>)",
        warning: "hsl(var(--color-background-warning) / <alpha-value>)",
        "light-warning":
          "hsl(var(--color-background-light-warning) / <alpha-value>)",
        "darker-warning":
          "hsl(var(--color-background-darker-warning) / <alpha-value>)",
        error: "hsl(var(--color-background-error) / <alpha-value>)",
        "light-error":
          "hsl(var(--color-background-light-error) / <alpha-value>)",
        "darker-error":
          "hsl(var(--color-background-darker-error) / <alpha-value>)",
      },
      icon: {
        primary: "hsl(var(--color-icon-primary) / <alpha-value>)",
        secondary: "hsl(var(--color-icon-secondary) / <alpha-value>)",
        tertiary: "hsl(var(--color-icon-tertiary) / <alpha-value>)",
        placeholder: "hsl(var(--color-icon-placeholder) / <alpha-value>)",
        negative: "hsl(var(--color-icon-negative) / <alpha-value>)",
        "base-primary": "hsl(var(--color-icon-base-primary) / <alpha-value>)",
        "darker-primary":
          "hsl(var(--color-icon-darker-primary) / <alpha-value>)",
        info: "hsl(var(--color-icon-info) / <alpha-value>)",
        "darker-info": "hsl(var(--color-icon-darker-info) / <alpha-value>)",
        success: "hsl(var(--color-icon-success) / <alpha-value>)",
        "darker-success":
          "hsl(var(--color-icon-darker-success) / <alpha-value>)",
        warning: "hsl(var(--color-icon-warning) / <alpha-value>)",
        "darker-warning":
          "hsl(var(--color-icon-darker-warning) / <alpha-value>)",
        error: "hsl(var(--color-icon-error) / <alpha-value>)",
        "darker-error": "hsl(var(--color-icon-darker-error) / <alpha-value>)",
      },
      brand: {
        primary: "hsl(var(--brand-primary) / <alpha-value>)",
        "primary-light": "hsl(var(--brand-primary-light) / <alpha-value>)",
        "primary-dark": "hsl(var(--brand-primary-dark) / <alpha-value>)",
        success: "hsl(var(--brand-success) / <alpha-value>)",
        "success-light": "hsl(var(--brand-success-light) / <alpha-value>)",
        "success-dark": "hsl(var(--brand-success-dark) / <alpha-value>)",
        danger: "hsl(var(--brand-danger) / <alpha-value>)",
        "danger-light": "hsl(var(--brand-danger-light) / <alpha-value>)",
        "danger-dark": "hsl(var(--brand-danger-dark) / <alpha-value>)",
        warning: "hsl(var(--brand-warning) / <alpha-value>)",
        "warning-light": "hsl(var(--brand-warning-light) / <alpha-value>)",
        "warning-dark": "hsl(var(--brand-warning-dark) / <alpha-value>)",
        notice: "hsl(var(--brand-notice) / <alpha-value>)",
        "notice-light": "hsl(var(--brand-notice-light) / <alpha-value>)",
        "notice-dark": "hsl(var(--brand-notice-dark) / <alpha-value>)",
        info: "hsl(var(--brand-info) / <alpha-value>)",
        "info-light": "hsl(var(--brand-info-light) / <alpha-value>)",
        "info-dark": "hsl(var(--brand-info-dark) / <alpha-value>)",
        approve: "hsl(var(--brand-approve) / <alpha-value>)",
        "approve-light": "hsl(var(--brand-approve-light) / <alpha-value>)",
        "approve-dark": "hsl(var(--brand-approve-dark) / <alpha-value>)",
        focus: "hsl(var(--brand-focus) / <alpha-value>)",
        separator: "hsl(var(--brand-separator) / <alpha-value>)",
        border: "hsl(var(--brand-border) / <alpha-value>)",
      },
    },
    fontSize: {
      xs: ["0.75rem", { lineHeight: "1rem" }],
      sm: ["0.875rem", { lineHeight: "1.25rem" }],
      base: ["1rem", { lineHeight: "1.5rem" }],
      lg: ["1.125rem", { lineHeight: "1.75rem" }],
      xl: ["1.25rem", { lineHeight: "1.75rem" }],
      "2xl": ["1.5rem", { lineHeight: "2rem" }],
      "3xl": ["1.75rem", { lineHeight: "2.25rem" }],
      "4xl": ["2rem", { lineHeight: "2.5rem" }],
      "5xl": ["2.25rem", { lineHeight: "2.75rem" }],
      "6xl": ["3rem", { lineHeight: "1" }],
      "7xl": ["4rem", { lineHeight: "1" }],
    },
    screens: {
      xs: "360px",
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1440px",
    },
    extend: {
      animation: {
        enter: "enter 200ms ease-out",
        leave: "leave 150ms ease-in forwards",
        overlay: "overlay 150ms cubic-bezier(0.16, 1, 0.3, 1)",
      },
      keyframes: {
        enter: {
          "0%": { transform: "scale(0.9)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        leave: {
          "0%": { transform: "scale(1)", opacity: "1" },
          "100%": { transform: "scale(0.9)", opacity: "0" },
        },
        overlay: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      fontFamily: {
        sans: ["Inter var", ...defaultTheme.fontFamily.sans],
      },
      spacing,
      maxWidth: spacing,
      minHeight: { ...defaultTheme.spacing, ...spacing },
      borderRadius: { "2.5xl": "20px" },
      strokeWidth: {
        2.5: "2.5",
      },
      ringWidth: {
        1.5: "1.5px",
      },
    },
  },
} satisfies Config;
