import * as React from "react";
import { toCanvas as qrToCanvas } from "qrcode";

/**
 * @typedef {Object} QRCodeProps
 * @prop {string} text The text to be generated by QR Code
 * @prop {number=} width The width of the QR Code in px. Default width is set to 240px.
 */
/** @param {QRCodeProps} props */
export function QrCode({ text, width = 240 }) {
  const canvasRef = React.useRef();

  React.useEffect(() => {
    qrToCanvas(canvasRef.current, text, { width });
  }, [text, width]);

  return <canvas ref={canvasRef} />;
}
